### ISSUE TITLE
Why vocab_size in bert_config.json is not same as vocab.txt 

### ISSUE THREAD

**Issue by liushui9404** [tchayintr/thbert#1]
We can see vocab_size in bert_config.json is 25004 , but there are 128004 words in vocab.txt,Why?

**Comment by tchayintr** [comment]
Both BERT base and large are pretrained with the vocabulary size of 128000. It seems I mistyped the config file when I was prepared the file with a good structure so I have revised the file. 
Thanks to let me know.
