### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by tanadate-rungsripattanaporn** [tchayintr/thbert#3]
Hello, I try to import by transformer but still have a problem. Need some suggestion, thanks!

**Comment by tchayintr** [comment]
Could you specify the problem? e.g. errors and logs.
By the way, these were trained on Tensorflow 2.0 so I am not sure if it properly works on Transformers (pytorch) from huggingface. 
Yet I have not tried with the transformers by myself. 

You might need to convert the original BERT checkpoint into a pytorch checkpoint by using the following script 
[convert_bert_original_tf_checkpoint_to_pytorch.py](https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py)
 
Hope this helps.
